[scene]
scene_filepath = "../scenes/scene.fbx"  # todo: implement fbx loading

[sampling]
samples_per_pixel = 32
max_bounces = 10

direct_clamp = 100
indirect_clamp = 10

[saving]
save_on_samples = [100, 1000, 10000, 100000, 1000000]  # list of integers
save_on_times = [10.0]  # list of floats. unit: seconds

[postprocessing]
[postprocessing.bloom]
radius = 6.0  # percent width of the image. standard deviation of gaussian blur
threshold = 1.0  # threshold at which to apply bloom
intensity = 0.025  # [0, 1], but recommended to be less than 0.05

[postprocessing.tonemap]
exposure = 1.0  # exposure. 0 is no change. calculated by color_out = color_in * 2^exposure