[camera]
[camera.dof]
focus_dist = 2.0
defocus_multiplier = 0.0  # higher = more defocus

[sampling]
samples_per_pixel = 8
max_bounces = 16

direct_clamp = 100
indirect_clamp = 10

[saving]
save_on_samples = []  # list of integers
save_on_times = [60, 120, 180]  # list of floats. unit: seconds

[postprocessing]
[postprocessing.bloom]
radius = 5.0  # percent width of the image. standard deviation of gaussian blur
threshold = 1.0  # threshold at which to apply bloom
intensity = 0.05  # [0, 1], but recommended to be less than 0.05

[postprocessing.tonemap]
exposure = 1  # exposure. 0 is no change. calculated by color_out = color_in * 2^exposure